version: '3.8'
services:
  mongodb:
    image: mongo:latest
    env_file:
      - .env
    container_name: ${PROJECT_NAME}-mongodb
    hostname: ${PROJECT_NAME}-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongodata:/data/db
    restart: unless-stopped
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    healthcheck:
      test: ["CMD","mongo", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 1s
      retries: 5
  mongo-express:
    container_name: ${PROJECT_NAME}-mongo-express
    image: mongo-express:latest
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=${PROJECT_NAME}-mongodb
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASS}
      - ME_CONFIG_BASICAUTH_USERNAME=mexpress
      - ME_CONFIG_BASICAUTH_PASSWORD=mexpress
    ports:
      - '8081:8081'
    restart: unless-stopped
    volumes:
      - mongodata:/data/db
  server:
    container_name: ${PROJECT_NAME}-app
    build:
      context: ./
    volumes:
      - .:/code
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
volumes:
  mongodata:
    name: ${MONGO_DB}